### ISSUE TITLE
CodePath Guide

### ISSUE THREAD

**Issue by abhinav-adtechs** [GDGAhmedabad/Learning-Resources#134]
I think we can import a lot of stuff from here. Please See.

https://github.com/codepath/android_guides/wiki

**Comment by PareshMayani** [comment]
hmm yes we can but they have prepared a solid repo with contents too, here we are just trying to collect links for the reference!

1) We can include their android guides in Useful links section
2) Some libraries or frameworks or tools from https://github.com/codepath/android_guides/wiki/Must-Have-Libraries and https://github.com/codepath/android_guides/wiki/Popular-External-Tools

**Comment by abhinav-adtechs** [comment]
Yes, true.
