### ISSUE TITLE
Proposal: List of cross platform app

### ISSUE THREAD

**Issue by pranaypatel512** [GDGAhmedabad/Learning-Resources#148]
Can we add List of cross platform apps?
See below link.
[Awesome-Cross-Platform-Apps](https://github.com/Juude/Awesome-Cross-Platform-Apps)

**Comment by PSanni** [comment]
I do suggest to create Framework section and put list inside.

**Comment by PareshMayani** [comment]
These are the solutions/frameworks for building apps cross platform apps. I agree with @PSanni or we can create a "Hybrid Framework" section same as Android, python and other technologies.
