### ISSUE TITLE
Add Interview Resources

### ISSUE THREAD

**Issue by abs51295** [GDGAhmedabad/Learning-Resources#186]
Should we add a separate folder for interview preparation?

**Comment by PareshMayani** [comment]
sure we can do that, it would be at least helpful to students and freshers.

**Comment by abs51295** [comment]
@PareshMayani I am thinking of the following folder structure:

- Interview Preparation

    -  Data Structures and Algorithms

    -  Android

     - iOs

     - System Design etc.

**Comment by rathodchintan** [comment]
@abs51295 I think adding 
"Android" -> "Interview Preparation"
"iOS" -> "Interview Preparation" 
would be better solution.

**Comment by abs51295** [comment]
@rathodchintan Data Structures and Algorithms and System Design (For experienced people) are a common part of every interview so I think they should be added separately.

**Comment by PareshMayani** [comment]
@abs51295 yes let's create an "Interview-preparation" directory and push resources. It would be quite helpful to our next generation of engineers. Let's do it!
