### ISSUE TITLE
Add courses materials for Operating System

### ISSUE THREAD

**Issue by AnaghHegde** [GDGAhmedabad/Learning-Resources#201]
Hi, I found a tutorials for OS course - [https://oscourse.github.io/](https://oscourse.github.io/). I think its useful.

**Comment by rathodchintan** [comment]
@AnaghHegde Thanks for sharing. Can you create a PR on respective directory. So that we can merge it.

**Comment by AnaghHegde** [comment]
@rathodchintan I couldn't find any directory for OS. So should I need to create a directory or any other suggestions ?

**Comment by PareshMayani** [comment]
Yes create a directory having required files like blogs.md, books.md. Take reference of Android directory and follow the same https://github.com/GDGAhmedabad/Learning-Resources/tree/master/android.

Thanks and looking forward for your contribution!
