### ISSUE TITLE
Link all other files in repo's README.md

### ISSUE THREAD

**Issue by aviaryan** [GDGAhmedabad/Learning-Resources#51]
I propose a structure like this . 
- Angular
- Git
  - [Books]()
  - [Courses]()
  - [Podcasts]()
- Wordpress
  - [Books]()
  - [Blogs]()

This will hopefully make finding what you want much more convenient.

**Comment by PareshMayani** [comment]
Yes this is in our plan! Thanks for the suggestion.

**Comment by PSanni** [comment]
Let's try me finger on that. :wink:

**Comment by PareshMayani** [comment]
@aviaryan let's do it now since it's stable and silent so let's do that now!

**Comment by aviaryan** [comment]
@PareshMayani Sure. I will send a PR.
