### ISSUE TITLE
Proposed guidelines to avoid confusion around contributors. 

### ISSUE THREAD

**Issue by PSanni** [GDGAhmedabad/Learning-Resources#78]
I have seen commits, that are messing things like contributor interchanging section for respected items. 
So here i have prepared guide, which should be included in contribution guidelines. 

- Books : Original publisher URL of any book, it can be by amazon, Oreilly, head first or any other publisher. Please don't share PDF/HTML/ePub file shared over any free e-book site or drive link or dropbox link.
- Courses : A course is a learning material which is not a book and where there is no interactive tool embedded in the site. 
- Interactive Tutorials : An interactive website which lets the user type code or commands and evaluates the result.
- Tools: It's kind a software which are helpful in writing,debugging,and testing code. 
- Video tutorials are single topic at single time. 
- Experts are individual, who holds the reputation in respected area. 
- Blogs are something which covers personal experience, they are neither tutorial or website. EX:- My personal experience with code optimization in python. 
- Useful links are URL's which belongs to item official guide, documentation, discussion channel, forum, blogs etc. 

Please,share your views. :smile:

**Comment by PareshMayani** [comment]
Hi Sanny,

It was in my list :) Below is one point that I would like you to update your details with:

Books : Original publisher URL of any book, it can be by amazon, Oreilly, head first or any other publisher. Please don't share PDF/HTML/ePub file shared over any free e-book site or drive link or dropbox link.

**Comment by PSanni** [comment]
Indeed (Y)

**Comment by PareshMayani** [comment]
Thanks @PSanni for the suggestion. Appreciate it! We have updated readme file with the suggested points.
