### ISSUE TITLE
Proposal: Adding Ionic as a platform

### ISSUE THREAD

**Issue by chintansoni202** [GDGAhmedabad/Learning-Resources#79]
Hello Sir,
Greetings !!!

As we have been observing, [Ionic](http://ionicframework.com/) now, is not just a framework, but it has grown to a platform for web developers to play with. It is recommended that we add this as a folder with the rest of the platforms.

Thanks and warm regards,

Chintan Soni

**Comment by PSanni** [comment]
I think Ionic is HTML5 based mobile app framework, Which should be included under HTML or android section. But separate section for any framework seems bad idea.

**Comment by rathodchintan** [comment]
@PSanni you are right. Lonic is hybrid app framework.

**Comment by PareshMayani** [comment]
How about creating a cross platform directory, then we can list down all the cross platform development technologies and frameworks! 

What do you say?

**Comment by chintansoni202** [comment]
That sounds great, @PareshMayani sir.

**Comment by PSanni** [comment]
@PareshMayani Than we might have need to change whole repository structure. Because there are many technologies already in repo, which belongs to "Cross-Platform" category.

**Comment by PareshMayani** [comment]
@PSanni yes true you are right! Let's not create a "Cross platform" directory right now and let's keep all the directories on the root level only. Will define a directory structure later!

**Comment by PSanni** [comment]
Yup, Great idea.

**Comment by PareshMayani** [comment]
@chintansoni202 you can go ahead and create a separate directory for Ionic framework!

**Comment by PSanni** [comment]
Under BigData section. Am i correct ????  :smile:

**Comment by PareshMayani** [comment]
As far as I know, IONIC is a web framework and not related to big data! Please correct me if I am wrong!

**Comment by chintansoni202** [comment]
Yes @PareshMayani Sir. You are right. Its a mobile cross platform framework built on top web technologies. It is not related to Big Data. We will have "Ionic" folder with rest of our technologies, on the same hierarchical level as android, ios, etc.

**Comment by PSanni** [comment]
Sry my bad, i mean Under HTML section. 
@chintansoni202 Better to put it under HTML folder. Because if we compare it with other than Django is also same level candidate.
